/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MainGame from "./script/MainGame"
import BoxItem from "./script/BoxItem"
import ClickBox from "./script/ClickBox"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedheight";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="center";
    static startScene:any="Main/Main.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/MainGame.ts",MainGame);
        reg("script/BoxItem.ts",BoxItem);
        reg("script/ClickBox.ts",ClickBox);
    }
}
GameConfig.init();